### PR TITLE
Added tips for handling hidden state.

### PR DESCRIPTION
**Pull request by strawb3rryx7**

### CODE REVIEW

**Comment by strawb3rryx7** [comment]
I’m using your library on my current work and i guess, that’s a good point
to handle hidden state of tab bar on workflow. But your choice. 🙌🏼

**Comment by hemangshah** [comment]
@strawb3rryx7 - Glad to hear that, you're using HHTabBarView. I am only concern if we really need to provide that information inside the README? If yes, can we improve it a bit more understandable with a description that, why we need to write that line inside the `viewWillAppear`?

Looking forward to hearing from you. And once again, I am happy to have all the contributors to this project as I believe, we all together can provide a classy tabbar solution.

**Comment by strawb3rryx7** [comment]
Thanks for your quick answers, I discovered that problem, sometimes tab bar
being in stuck and always stays on bottom. (that’s disappears visually, tab
bar controller’s default tab bar is still stays in there.)

and other issue,

I think it is necessary to make arrangements for positioning the tab bar. I
experienced some problems while using auto layout in my work I applied to
hacky solutions for fixing issues.

**Comment by hemangshah** [comment]
@strawb3rryx7 , thanks for the detailed response.

Can you please list all of the issues and their possible solutions so I can make the relevant changes in the tab bar?

**Comment by strawb3rryx7** [comment]
Of course, I’ll send everything about that when I woken up. 🖐🏼

**Comment by hemangshah** [comment]
Sounds good! Thanks @strawb3rryx7

**Comment by strawb3rryx7** [comment]
You’re welcome, we’ll do our best!

**Comment by hemangshah** [comment]
Hi, @strawb3rryx7 - any updates from you?

**Comment by strawb3rryx7** [comment]
Hello @hemangshah, Thanks for remind me. I'll send message in few days. I was busy for lots of work :'( Don't worry.

**Comment by hemangshah** [comment]
Hi @strawb3rryx7 - it would be great if you can send an update now?

**Comment by hemangshah** [comment]
@strawb3rryx7, believing that you're very busy these days, please feel free to comment if you want me to reopen.

**Comment by strawb3rryx7** [comment]
Sorry, I'm really busy to contribute that, but i'm keeping in my mind. I'll
reopen. Thanks for reminding again.

2018-03-20 15:25 GMT+03:00 Hemang <notifications@github.com>:

**Pull request closed without merging**
